version: 2
updates:
  - package-ecosystem: "pip" # Poetry gebruikt pip
    directory: "/" # De root directory of pas aan als nodig
    schedule:
      interval: "daily"
    # Groeperingsinstellingen
    groups:
      all-dependencies:
        patterns:
          - "*"
