[tool.poetry]
name = "finance-dashboard"
version = "0.1.0"
description = ""
authors = ["thomastunc <thomastunc@hotmail.com>"]
readme = "README.md"
packages = []

[tool.poetry.dependencies]
python = "^3.9"
bunq-sdk = "^1.14.18"
python-dotenv = "^1.0.1"
google-cloud-bigquery = "^3.26.0"
pandas-gbq = "^0.23.2"
google-auth = "^2.35.0"
degiro-connector = ">=2.0.23"
bs4 = "^0.0.2"
currencyconverter = "^0.17.32"
moralis = "^0.1.49"
coinbase = "^2.1.0"



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
