[tool.poetry]
name = "finance-dashboard"
version = "0.1.1"
description = ""
authors = ["thomastunc <thomastunc@hotmail.com>"]
readme = "README.md"
packages = []

[tool.poetry.dependencies]
python = "^3.11"
bunq-sdk = "^1.14.18"
python-dotenv = "^1.0.1"
google-cloud-bigquery = "^3.29.0"
pandas-gbq = "^0.27.0"
google-auth = "^2.38.0"
bs4 = "^0.0.2"
currencyconverter = "^0.18.3"
moralis = "^0.1.49"
degiro-connector = "^3.0.23"
protobuf = "^5.29.3"
coinbase-advanced-py = "^1.8.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
